### PR TITLE
Remove Foundation Framework from NDP

### PR DESCRIPTION
**Pull request by benhayehudi**
Since we have installed and are using Volta, we now have two CSS frameworks loaded into NDP: Volta and Foundation. In this PR, we remove the Foundation CSS framework.

### CODE REVIEW

**Comment by mheap** [comment]
@benhayehudi This is a good start.

I'd like to see a couple more things before we merge:

* A list of all of the unique page setups you've identified so that I know which pages to look at for layout/design issues
* Remove the old foundation classes from the HTML in addition to just removing the CSS

**Comment by benhayehudi** [comment]
> @benhayehudi This is a good start.
> 
> I'd like to see a couple more things before we merge:
> 
>     * A list of all of the unique page setups you've identified so that I know which pages to look at for layout/design issues
> 
>     * Remove the old foundation classes from the HTML in addition to just removing the CSS

Sure, both sound great. I'll get working on that. Thanks!

**Comment by benhayehudi** [comment]
@mheap, when you have a chance, could use your help in mocking the data for the `table` partial in its spec file. I'm having a hard time getting the structure right. 🙏

**Comment by benhayehudi** [comment]
List of ERB pages and their accompanying views that have been transitioned:

* `/app/views/static/migrate.html.erb` -> `migrate/tropo`
* `/app/views/search/results.html.erb` -> `/search`
* `/app/views/api_errors/index.html.erb` -> `/api-errors`

Additionally, `tab_filter.rb` has been updated and the Foundation JS imports have been removed from the asset pipeline.

**Comment by benhayehudi** [comment]
## Pages:Views

### Searched

- [x]      '/*landing_page', to: 'static#default_landing'

- [x]        /signout', to: 'sessions#destroy'

- [x]       post '/jobs/code_example_push', to: 'jobs#code_example_push'

- [x]        post '/jobs/open_pull_request', to: 'jobs#open_pull_request'

- [x]        '/coverage', to: 'dashboard#coverage'

- [x]       '/stats', to: 'dashboard#stats'

- [x]        '/stats/summary', to: 'dashboard#stats_summary'

- [x]       '/tutorials/(:code_language)', to: 'tutorials#index'

- [x]       '/tutorials/*document(/:code_language)', to: 'tutorials#show'

- [x]        '/documentation', to: 'static#documentation'

- [x]        /migrate/tropo/(/*guide)', to: 'static#migrate_details'

- [x]        '/legacy', to: 'static#legacy'

- [x]        '/team', to: 'static#team'

- [x]        '/community/slack', to: 'slack#join'

- [x]        post '/community/slack', to: 'slack#invite'

- [x]        /tools', to: 'static#tools'

- [x]        '/community', to: 'static#community'

- [x]        '/community/past-events', to: 'static#past_events'

- [x]        '/feeds/events', to: 'feeds#events'

- [x]         '/extend', to: 'extend#index'

- [x]        '/extend/:title', to: 'extend#show'

- [x]        match '/search', to: 'search#results'

- [x]         '/api-errors', to: 'api_errors#index'

- [x]         '/api-errors/generic/:id', to: 'api_errors#show'

- [x]       '/api-errors/*definition', to: 'api_errors#index_scoped'

- [x]        '/api', to: 'api#index'

- [x]        '/api/*definition(/:code_language)', to: 'open_api#show'

- [x]        '/task/(:task_name)(/*task_step)(/:code_language)', to: 'task#index'

- [x]       '/*product/api-reference', to: 'markdown#api'

- [x]        /contribute, to: 'markdown#show'

- [x]        '*unmatched_route', to: 'application#not_found'

- [x]        root 'static#landing'

### Needed to Fix?

- [ ]      '/*landing_page', to: 'static#default_landing'

- [ ]      '/signout', to: 'sessions#destroy'

- [ ]      post '/jobs/code_example_push', to: 'jobs#code_example_push'

- [ ]      post '/jobs/open_pull_request', to: 'jobs#open_pull_request'

- [ ]     '/coverage', to: 'dashboard#coverage'

- [ ]     '/stats', to: 'dashboard#stats'

- [ ]     '/stats/summary', to: 'dashboard#stats_summary'

- [ ]     '/tutorials/(:code_language)', to: 'tutorials#index'

- [ ]     '/tutorials/*document(/:code_language)', to: 'tutorials#show'

- [ ]     '/documentation', to: 'static#documentation'

- [x]     /migrate/tropo/(/*guide)', to: 'static#migrate_details'

- [ ]      '/legacy', to: 'static#legacy'

- [ ]      '/team', to: 'static#team'

- [ ]      '/community/slack', to: 'slack#join'

- [ ]      post '/community/slack', to: 'slack#invite'

- [ ]      /tools', to: 'static#tools'

- [ ]      '/community', to: 'static#community'

- [ ]      '/community/past-events', to: 'static#past_events'

- [ ]     '/feeds/events', to: 'feeds#events'

- [ ]      '/extend', to: 'extend#index'

- [ ]      '/extend/:title', to: 'extend#show'

- [ ]      match '/search', to: 'search#results'

- [x]     '/api-errors', to: 'api_errors#index'

- [x]     '/api-errors/generic/:id', to: 'api_errors#show'

- [x]     '/api-errors/*definition', to: 'api_errors#index_scoped'

- [ ]      '/api', to: 'api#index'

- [ ]      '/api/*definition(/:code_language)', to: 'open_api#show'

- [ ]      '/task/(:task_name)(/*task_step)(/:code_language)', to: 'task#index'

- [ ]      '/*product/api-reference', to: 'markdown#api'

- [ ]      /contribute, to: 'markdown#show'

- [ ]     '*unmatched_route', to: 'application#not_found'

- [ ]      root 'static#landing'

**Pull request merged**
