### PR TITLE
Update nexmo-oas-renderer to 0.4.0

### PR DESCRIPTION
**Pull request by mheap**
## Description

Bump OAS renderer to 0.4.0 to add fix for rendering `oneOf` response field descriptions

## Deploy Notes

N/A

### CODE REVIEW

**Comment by fabianrbz** [comment]
@mheap  can you take a look? I fixed the styles in NDP

**Comment by mheap** [comment]
Screen Shot 2019-09-02 at 15 04 45

There's a white border around the tabs on the Verify docs

**Comment by fabianrbz** [comment]
looking, there's an issue with `assets:precompile`

**Comment by fabianrbz** [comment]
Related https://github.com/Nexmo/nexmo-oas-renderer/pull/21

**Comment by fabianrbz** [comment]
@mheap the issue is now fixed, asset precompilation was failing in prod

**Comment by mheap** [comment]
Great, thanks!

Could we fix the white border around the tabs on the Verify reference (see screenshot above)?

**Comment by fabianrbz** [comment]
@mheap that should have been fixed as part of the last commit. Are you still seeing that? If so, which browser are you using?

**Comment by mheap** [comment]
Yep still seeing it on https://nexmo-developer-pr-1935.herokuapp.com/api/verify in Chrome

**Comment by mheap** [comment]
I'm going to merge this as it's an improvement on what we have. Please open another PR to fix the above whitespace issue

**Pull request merged**
