### PR TITLE
Updates to DevTV Page

### PR DESCRIPTION
**Pull request by ruskibenya**
Parked devtv landing page. Hid content calendar. Added an alert bar to let users know this page is dead.

### CODE REVIEW

**Comment by abdulajet** [comment]
I think we should maybe use a redirect to another page rather than the banner it seems a bit heavy-handed? same for the other PR.

Otherwise friendlier language would be good. "To get the latest visit xyz" rather than "not maintained"

**Comment by ruskibenya** [comment]
@abdulajet @marcoranieri How about this?
Screen Shot 2022-03-10 at 21 37 57

**Comment by kellyjandrews** [comment]
Well - I wish I'd looked here before the other PRs 🙁

**Comment by kellyjandrews** [comment]
Hey Ben - you can add redirects here I think  - https://github.com/Nexmo/nexmo-developer/blob/main/config/redirects.yml

**Review by marcoranieri — APPROVED** [review]

**Pull request merged**
