### PR TITLE
Remove constraints from renderer.

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

* From now on, constraints are only valid for NDP and should be updated
here.
* Redirects are up to date with what we had in the renderer.
* Constraints now include everything that was defined in the renderer.

## Deploy Notes

We need to release https://github.com/Nexmo/nexmo-oas-renderer/pull/35 first, and then bump its version here.

### CODE REVIEW

**Comment by fabianrbz** [comment]
@mheap I;m not sure how do you want to handle the issue with the api-errors, most of those are for   APIs that are in beta.

**Comment by mheap** [comment]
@fabianrbz What's the issue with `api-errors`?

**Comment by fabianrbz** [comment]
@mheap the check that is failing

**Comment by fabianrbz** [comment]
@mheap I ended up skipping the subaccounts from the rake task as it was still failing. It requires the error to be in the page :/

**Comment by mheap** [comment]
@fabianrbz I'll approve this to keep us moving, but we do need to fix those broken links by adding `x-errors` to the subaccounts YAML

**Pull request merged**
