### PR TITLE
Updated api-errors adding 10dlc

### PR DESCRIPTION
**Pull request by niati**
## Description

Updated the api-errors adding 10DLC errors.

### CODE REVIEW

**Comment by pardel** [comment]
@niati  should this error not reside inside api_specifications? /cc @EDDYMENS

**Comment by EDDYMENS** [comment]
> @niati should this error not reside inside api_specifications? /cc @EDDYMENS

@pardel This change is ok since we only pull API definitions from the `api_specfications` repo into a subdirectory within the  `_open_api` directory ie: _open_api/api_spec`. Everything else including errors live directly in the `_open_api` directory.

**Comment by EDDYMENS** [comment]
> > @niati should this error not reside inside api_specifications? /cc @EDDYMENS
> 
> @pardel This will be ok since we only pull API definitions from the `api_specfications` repo into a subdirectory within `_open_api` ie: `_open_api/api_spec`. Everything else including errors live directly in the `_open_api` directory.

Just realized the dedicated errors page doesn't work for specific API selection https://developer.vonage.com/api-errors/10dlc and also we already have the error messages directly within the API definitions. https://developer.vonage.com/api/10dlc?theme=dark

So we might not need this PR anymore?

**Comment by pardel** [comment]
@EDDYMENS any update on this?

**Comment by EDDYMENS** [comment]
> @EDDYMENS any update on this?

Yes, 10DLC error messages are missing on the error page and this PR adds that

**Review by EDDYMENS — APPROVED** [review]

**Pull request merged**
