### PR TITLE
Procedure for linking FB page simplified

### PR DESCRIPTION
**Pull request by tbedford**
## Description

The page that links your Nexmo account and your Facebook page has been changed to only require API key and secret, rather than a JWT. This drastically simplifies the procedure for linking your FB page and Nexmo app. The partial has been reworked, along with a step in the new-style tutorial. The Use Cases have been modified to use the rewritten partial.

Note: The Use Cases will appear a little odd due to the two-part nature of the linking process, but these Use Cases will be converted at some point to use the step-by-step mechanism anyway.

Note: The External Accounts API spec also has some links that need changing. Fixed in API-spec repo and pointer updated here.

- [x] [This PR](https://github.com/Nexmo/api-specification/pull/246) needs to be merged first, then this one updated.

## Review

Pages to review:

- [ ] [Facebook concept](https://nexmo-developer-pr-2350.herokuapp.com/messages/concepts/facebook)
- [ ] [Dispatch API step-by-step](https://nexmo-developer-pr-2350.herokuapp.com/dispatch/tutorials/sending-facebook-message-with-failover/olympus/link-facebook-page)
- [ ] [Product info use case](https://nexmo-developer-pr-2350.herokuapp.com/use-cases/fbm-product-info#link-your-application-to-your-facebook-page)
- [ ] [Send message use case](https://nexmo-developer-pr-2350.herokuapp.com/use-cases/sending-facebook-messenger-messages-with-messages-api#part-1-link-your-facebook-page-to-your-nexmo-account)
- [ ] [External accounts spec](https://nexmo-developer-pr-2350.herokuapp.com/api/external-accounts#CreateMessengerAccount)

### CODE REVIEW

**Comment by pardel** [comment]
This is awesome! (was on my todo list for this week)
Thank you @tbedford!

**Comment by tbedford** [comment]
@pardel - will you get a chance to look at this week?

**Comment by pardel** [comment]
@tbedford sorry for the delay - will do it today.

**Comment by tbedford** [comment]
Thanks a lot Paul!

**Pull request merged**
