### PR TITLE
Update the images in spotlight.yml

### PR DESCRIPTION
**Pull request by martyndavies**
The images used in the Developer Spotlight page have been there for a while. Refreshing them with new links and images to latest posts.

## Description

Changed the links and images for the 4 images in the left column.

## Deploy Notes

No notes. Should merge straight in.

### CODE REVIEW

**Comment by tbedford** [comment]
I've fixed the failure to deploy issue.

**Comment by tbedford** [comment]
Is it possible to review before merging? If so, what is the URL of the page to be reviewed?

**Comment by mheap** [comment]
https://nexmo-developer-pr-1789.herokuapp.com/spotlight

**Comment by tbedford** [comment]
Thanks Michael, had just found it before your comment by looking at one of Fabian's PRs!

**Pull request merged**
