### PR TITLE
Update Ruby examples to nexmo-ruby v5

### PR DESCRIPTION
**Pull request by timcraft**
PR to update the Ruby code examples to nexmo-ruby v5--there are a number of backwards incompatible changes from v4, as detailed here:

https://github.com/Nexmo/nexmo-ruby/blob/master/CHANGES.md#500
https://github.com/Nexmo/nexmo-ruby/blob/master/5.0-Upgrade.md

### CODE REVIEW

**Comment by adambutler** [comment]
@judy2k I mistook the merged above to be this PR...

@timcraft Please hold off merging this for now. I need to check if any code extracts that use `from_line` and `to_line` require updating to align with changes.

**Comment by timcraft** [comment]
@adambutler I can't merge it 😊 Let me know if it needs any changes (or feel free to edit).

**Comment by adambutler** [comment]
Sorry it took me so long to get to this. I've gone through these changes in fine detail and tested everything to ensure the examples work.

It's fairly rare for a big change like this to be made without any tweaks required but I'm really happy with the thoroughness of the changes made in this PR and am happy to merge it. Great work @timcraft !

Since the `compare` part of this PR has since been removed and there was a merge conflict to deal with there has been a new PR opened to replace this one at #606.

**Comment by timcraft** [comment]
@adambutler Woohoo, thanks! I was going to fix the merge conflict but you beat me to it.

I think #592 can be closed as well.

**Pull request merged**
