### PR TITLE
Fixed print pages

### PR DESCRIPTION
**Pull request by AraanBranco**
## Description

I put a media query to show css when printing.
#795

### CODE REVIEW

**Comment by lornajane** [comment]
This is a nice start, but can we just focus on the content? My printout still has headers and menus and things on, which aren't helpful in a printed format since they're not clickable. I've attached an example to show what I get.
[Nexmo Developer _ Text to Speech.pdf](https://github.com/Nexmo/nexmo-developer/files/2500886/Nexmo.Developer._.Text.to.Speech.pdf)

**Comment by AraanBranco** [comment]
No problem, I'll get it to do, you have another channel of contact, that we can go through all the content of what you want together? =)

**Comment by lornajane** [comment]
Our process is to keep the conversation about each pull request with the pull request. The print view should cover just the content and not the header, navigation or footer. Please let me know if you have any questions.

**Comment by AraanBranco** [comment]
@lornajane i added one file to manipulate the css for print, check and see it resolves
[Nexmo Developer _ Text to Speech.pdf](https://github.com/Nexmo/nexmo-developer/files/2522615/Nexmo.Developer._.Text.to.Speech.pdf)

**Comment by AraanBranco** [comment]
@lornajane I left the page 100% and removed the feedback module, I think it would not be necessary to leave it, another doubt .. I shot the side menu and leave only the content itself, or not?

**Comment by lornajane** [comment]
I think the side menu should be removed too. It isn't useful in printed format. Thanks!

**Comment by AraanBranco** [comment]
@lornajane I already finished taking ... but forgot, see how it was =) [Nexmo Developer _ Overview.pdf](https://github.com/Nexmo/nexmo-developer/files/2526808/Nexmo.Developer._.Overview.pdf)
Was the element of css: `#Vlt-sidenav`

**Comment by mheap** [comment]
This is awesome, thanks @AraanBranco!

**Pull request merged**
