### PR TITLE
Conv updates

### PR DESCRIPTION
**Pull request by kellyjandrews**
## Description

Correcting `@vonage/sdk@beta` to `@vonage/server-sdk@beta`

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by kellyjandrews** [comment]
sorry for the fire drill, but literally just realized I used the wrong npm package name.

**Comment by kellyjandrews** [comment]
Working on the conflicts - really confused as to why

**Comment by kellyjandrews** [comment]
@marklewin any chance we can get this pushed through?

**Review by marklewin — APPROVED** [review]
Yes, sorry for the delay! LGTM 👍

**Pull request merged**
