### PR TITLE
Updates for Java submodules

### PR DESCRIPTION
**Pull request by yallen011**
## Description

Made updates for the java code snippets

### CODE REVIEW

**Comment by mheap** [comment]
I clicked on a couple of snippets to review and the line numbers weren't accurate for some of them. Please check all snippets, including the `Initialize your dependencies` section (named `client` in the YAML file)

**Review by mheap — CHANGES_REQUESTED** [review]
I clicked on a couple of snippets to review and the line numbers weren't accurate for some of them. Please check all snippets, including the `Initialize your dependencies` section (named `client` in the YAML file)

**Comment by yallen011** [comment]
I just realized that yesterday I forgot to make the PR for the code snippet changes that I made while reviewing this PR. I made a PR for those changes and linked them to this PR. So for those few, I matched to code lines up to what it will look like when that PR is submitted so that nexmo-developer will reflect those changes.

**Comment by dragonmantank** [comment]
Looks like the deployment actually failed, even though CI says it passed. Can't get any of the code snippet pages to load on the deployed version.

**Comment by lornajane** [comment]
I had this problem with some other code snippets as well ... @fabianrbz can you help us understand if the error pages are because of a problem in this branch or something similar to the problem I had with the curl code snippets?

**Comment by fabianrbz** [comment]
@lornajane @dragonmantank the problem occurs when you visit `/<product>/code-snippets` because we are not generating the DB in review apps and redirects use it under the hood. You can access using the sidenav.

**Pull request merged**
