### PR TITLE
Redirect all "building-blocks/" urls to "code-snippets/" long term fix

### PR DESCRIPTION
**Pull request by benhayehudi**
This PR is a follow-up to #1578, wherein a more permanent solution is presented here to redirect all `building-blocks/` old URLs to `code-snippets/` by using NDP's existing redirect functionality and expanding it to incorporate the old `building-blocks/` URLs.

### CODE REVIEW

**Comment by tbedford** [comment]
On testing:

https://nexmo-developer-pr-1581.herokuapp.com/numbers/building-blocks/buy-a-number/python

Gives a 404 but the code-snippets equivalent seems to work.

**Comment by benhayehudi** [comment]
> On testing:
> 
> https://nexmo-developer-pr-1581.herokuapp.com/numbers/building-blocks/buy-a-number/python
> 
> Gives a 404 but the code-snippets equivalent seems to work.

Can you please take another look? I added redirects for all language-specific paths now as well.

**Comment by tbedford** [comment]
Looks good. I've kicked the tyres and everything seems to work fine in the review app. Would like more than me to bash on it though please before I approve.

**Comment by benhayehudi** [comment]
> Looks good. I've kicked the tyres and everything seems to work fine in the review app. Would like more than me to bash on it though please before I approve.

Thank you! I've added @marklewin to review as well. Hopefully, he can kick the "tires" as well. 😆

**Comment by tbedford** [comment]
Nothing seems to be happening here so I'm going to approve and merge in the next 30 minutes or so...

**Pull request merged**
