### PR TITLE
Create jsconf-eu-coffee.yml

### PR DESCRIPTION
**Pull request by AlexLakatos**
## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by mheap** [comment]
Looks like there's a YAML error https://nexmo-developer-pr-1724.herokuapp.com/e/jsconf-eu-coffee

If you run it locally it'll show the error in development mode

**Comment by AlexLakatos** [comment]
I was having trouble running locally, that's why I did a PR. But I don't have access to heroku anymore to check the logs 😢

**Comment by mheap** [comment]
@benhayehudi Could you assist here? I don't have my laptop with me

**Comment by benhayehudi** [comment]
> @benhayehudi Could you assist here? I don't have my laptop with me

Sure, I'll look now.

**Comment by lornajane** [comment]
I was looking at this too as I realised Michael and Alex were both on the road, some minor fixes on top of Ben's real fix

**Pull request merged**
