### PR TITLE
[DEVX-1893] Turn careers page into a table.

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by mheap** [comment]
@fabianrbz What we have here is an improvement on what's live. Can we change the `We're hiring` link in the header to point to the new careers page and ship it? We can follow up with flags etc in a future PR

**Comment by mheap** [comment]
@fabianrbz What's the difference between IT and Information Technology?

**Comment by fabianrbz** [comment]
That's what we have in greenhouse, I believe IT is a sub-department of Information Technology. I'll be more than happy to merge them though.

**Comment by fabianrbz** [comment]
That's what we have in greenhouse, I believe IT is a sub-department of Information Technology. I'll be more than happy to merge them though.

**Pull request merged**
