### PR TITLE
Update SDK docs

### PR DESCRIPTION
**Pull request by dimitrisniras**

### CODE REVIEW

**Comment by dimitrisniras** [comment]
@horothesun @ash30 that's for you guys

**Comment by horothesun** [comment]
> @horothesun @ash30 that's for you guys

This PR should be rejected.
There's a problem in the way in which we generate the docs PR on `Nexmo/conversation-docs`: atm, we're not updating the https://github.com/Nexmo/conversation-docs/blob/master/ios/latest symlink.

As agreed with @dimitrisniras, I'll open a new PR on `Nexmo/conversation-docs` to fix the problem for this version and update the iOS SDK public release pipeline 👍

**Comment by fabianrbz** [comment]
@horothesun can you close this one when you do that?

**Comment by tbedford** [comment]
Closing as there seems to have been a major malfunction.

**Comment by horothesun** [comment]
> @horothesun can you close this one when you do that?

Unfortunately, it looks like I don't have the rights to close PRs on this repo 🙂

**Pull request closed without merging**
