### PR TITLE
Disable map in community pages if there are no events with locations

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by mheap** [comment]
@fabianrbz Is this the correct solution? What about when we want to add it back?

How about hiding the map if we have zero locations with an event scheduled?

**Comment by fabianrbz** [comment]
@mheap whatever we do, we'll need to revert the commit in order to add it back.
The issue with the locations is that every event has a country so we would need to check for the presence of a city. however add an `allow_blank` to the country dropdown,

**Comment by mheap** [comment]
If we hide the map when we have no locations we can keep it live forever and it'll appear/hide as required

Have we considered how we handle remote events?

**Comment by fabianrbz** [comment]
@mheap we could add a boolean column and a checkbox to the admin UI

**Comment by mheap** [comment]
I'll take your recommendation how to allow it, but I think it's going to be important in the near future

**Comment by myrsiningos** [comment]
All looks good to the Community team.

**Pull request merged**
