### PR TITLE
Update submodules to Vonage Code Snippets

### PR DESCRIPTION
**Pull request by mheap**
## Description

Update to the new Vonage submodules for code snippets

## Deploy Notes

N/A

### CODE REVIEW

**Comment by dragonmantank** [comment]
PHP snippets look good :+1:

**Comment by slorello89** [comment]
Need to move the dotnet snippets to the latest (had not merged them yet)

**Review by slorello89 — APPROVED** [review]
LGTM

**Review by dragonmantank — APPROVED** [review]
PHP code snippets look good

**Review by bencgreenberg — APPROVED** [review]

**Comment by kellyjandrews** [comment]
Do we plan on changing `NEXMO_KEY` and `NEXMO_SECRET` in the key section on these pages?

**Comment by mheap** [comment]
Yep, see https://github.com/Nexmo/nexmo-developer/pull/3206 (and review if you have time!)

**Comment by kellyjandrews** [comment]
Thank @mheap missed the reference in the middle.

**Review by kellyjandrews — APPROVED** [review]
Looks good for node

**Review by superdiana — APPROVED** [review]

**Comment by superdiana** [comment]
Looks good for python

**Comment by yallen011** [comment]
Here are my suggested changes: 

1. For the java install dependencies dropdown, can we change the dependency version to _5.5.0_ instead of _5.2.1_. This particular snapshot came from Create an Aplication code snippet.
image

2. Delivery Receipts and Receive an SMS _install dependencies_ dropdown still refers to the nexmo dependency _com.nexmo:client:5.2.1_

**Review by yallen011 — COMMENTED** [review]
Added changes in a PR

**Comment by mheap** [comment]
Looks like everyone has approved. I'll do one last spot check this afternoon by choosing snippets + languages randomly then merge.

Thanks for the work on this everyone 🙌

**Pull request merged**
