### PR TITLE
Add accessibilit to tabs

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

* Updates volta to include a11y features
* Highlights the selected tab in pink just to make it obvious and we can test it (we need to do something else here)
* Adds `role=tab` to tabs

## Note: experimental for now

### CODE REVIEW

**Comment by lornajane** [comment]
Oh this is helpful for what I reported in #2015 - I can read the NCCO reference now!

**Comment by fabianrbz** [comment]
great!
@lornajane @mheap I changed the colour to `lighter-blue`, do you think that it is necessary or should I just drop the highlighting?

**Comment by mheap** [comment]
@fabianrbz I see the light blue when focusing with a mouse, but not when using tab to select the item. Am I supposed to see it on the tab?

**Comment by fabianrbz** [comment]
@mheap I ended up removing the colour on focus, so it should use volta's styles

**Comment by lornajane** [comment]
I've approved but it looks like we're pointing to a branch in one of the dependencies so I wasn't sure if I should merge.

**Comment by fabianrbz** [comment]
@lornajane yes, we need to merge https://github.com/Nexmo/nexmo-oas-renderer/pull/40 first.
Can you look at that one?

**Comment by lornajane** [comment]
Great. Approved and merged over there but I assume you need to roll releases and update over here ... let me know if you need me to do anything else?

**Comment by fabianrbz** [comment]
I'll take it from here, thanks!

**Pull request merged**
