### PR TITLE
Client SDK tutorials reorg

### PR DESCRIPTION
**Pull request by tbedford**
## Description

An experimental PR. 

This PR better organizes the tutorials into in-app voice and in-app messaging subsections. This looks less cluttered and will help when we add more tutorials.

However, there's an issue - if you navigate to /client-sdk/tutorials you won't see any of the tutorials listed. What should we see? Should we see a subproduct pull down? Should we just put all tutorials at the top level?

@fabianrbz @marklewin your feedback most welcome! Thanks!

## Review

[Review app](https://nexmo-developer-pr-2240.herokuapp.com/client-sdk/overview)

### CODE REVIEW

**Comment by marklewin** [comment]
I like the reorg, @tbedford . I personally would be happy to see ALL Client SDK tutorials at `/client-sdk/tutorials` because I don't really see the benefit of cluttering up that dropdown, but I'm not precious about it!

**Comment by tbedford** [comment]
Thanks Mark. @fabianrbz is it possible to make that happen? So we'd have all Client SDK tutorials listed at `/client-sdk/tutorials`, but allow them to be grouped as they are in the TOC?

**Comment by fabianrbz** [comment]
@tbedford we can definitely make that happen

**Comment by tbedford** [comment]
Great, thanks @fabianrbz

**Comment by tbedford** [comment]
NDP work to be done under DEVX-1918

**Comment by tbedford** [comment]
Will do the reorg once NDP changes have been made.

**Pull request closed without merging**
