### PR TITLE
Send SMS with Unicode Building Block

### PR DESCRIPTION
**Pull request by tbedford**
## Description

Send SMS with Unicode building block with Curl and Python example code. 

Need to add at least Node code. [UPDATE: will be added some time in the future by DevRels]

### CODE REVIEW

**Comment by tbedford** [comment]
This is the old style of doing building blocks.

**Comment by lornajane** [comment]
Looking at adding the PHP and Node examples here - should we also be switching over to the new building blocks approach?  I can do that while I'm at it if you think so

**Comment by lornajane** [comment]
This work is a bit part-done while I wait for building blocks to be merged into the various quickstart repos - then I can close the loop and include the code examples.

**Comment by lornajane** [comment]
This was superceded by #846 since I had some issues rebasing this older branch

**Pull request closed without merging**
