### PR TITLE
Fix references to nexmo that appear in google indexing

### PR DESCRIPTION
**Pull request by pmmcls**
Fix references to nexmo that appear in google indexing

### CODE REVIEW

**Comment by fabianrbz** [comment]
@pmmcls is this ready for review?

**Comment by tbedford** [comment]
I thought code was in station and content in nexmo-developer.

**Comment by fabianrbz** [comment]
yeah, looks like this was branched off an old version of master. I'll update the PR

**Comment by fabianrbz** [comment]
@tbedford @pmmcls done

**Pull request merged**
