### PR TITLE
Volta

### PR DESCRIPTION
**Pull request by mheap**
Creating a review app for Volta (the visual refresh using the Vonage design system)

### CODE REVIEW

**Comment by leggetter** [comment]
Items in tabs are `display: none`

screen shot 2018-07-17 at 13 38 13

**Comment by mheap** [comment]
That's intended, it's a collapsible section. I mentioned to @BennyZ28 today that the indicator that it's collapsible is too far away on the right hand side and they're going to take a look

**Comment by leggetter** [comment]
@mheap there is no expand/collapse indicator for me

screen shot 2018-07-17 at 13 46 58

**Comment by mheap** [comment]
So there isn't! There was this morning when we did a run through

It's on the list to be fixed 👍

**Pull request merged**
