### PR TITLE
Make a call in < 15 mins JS setup

### PR DESCRIPTION
**Pull request by conshus**
## Description

Making changes to the "Making an in-app voice call" tutorial for the Make a call in < 15 mins goal
Adding a Glitch Webhook server option
Create the plan for the JS internal testing https://nexmoinc.atlassian.net/browse/DEVX-2475

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by tbedford** [comment]
@conshus - should this PR be closed now due to #2590 ?

**Comment by conshus** [comment]
Sure.

**Comment by conshus** [comment]
Should I delete the branch as well?

**Comment by tbedford** [comment]
Yes, I've done it.

**Pull request closed without merging**
