### PR TITLE
Add note that US numbers don't return portability/reachability info

### PR DESCRIPTION
**Pull request by marklewin**
## Description

@13webstreet (JP Chenot) advises that US numbers don't return portability/reachability info in NI Standard (and also, therefore, in NI Advanced)

## Deploy Notes

JP to check the following pages in test app:

- Overview
- Number Insight Standard building block
- Number Insight Advanced building block

Marking as "do not merge" until JP verifies

### CODE REVIEW

**Comment by 13webstreet** [comment]
I have confirmed with Paul Cook that reachability and portability is indeed available in the US in NI advanced. 
Therefore please update your changes as appropriate.

**Comment by marklewin** [comment]
Thanks @13webstreet. @lornajane could you please review and merge at your convenience?

**Comment by mheap** [comment]
@marklewin I believe that @13webstreet is saying that we *do* return reachability/portability information in NI advanced

**Comment by marklewin** [comment]
@13webstreet please clarify. This applies to US numbers only, right? And US numbers don't show portability or reachability info in the Standard API. Is there something different about US numbers in the Advanced API where they do show this info?

My presumption is that because Advanced is just an extension of Standard, whatever applies in Standard also applies in Advanced.

**Comment by 13webstreet** [comment]
Hi Mark.
The info IS available for US numbers in NI Advanced. Because NI Advanced does an API call to a 3rd party supplier, this information is available indeed.

**Comment by 13webstreet** [comment]
Great. This looks very good. Thank you.

**Comment by marklewin** [comment]
@mheap : JP approves the changes. If this looks good to you, please merge.

**Pull request merged**
