### PR TITLE
Curl additions for Voice Building Blocks

### PR DESCRIPTION
**Pull request by lornajane**
## Description

This PR brings in the new curl building blocks from their external repo, and adds the yml configuration to make them appear with the other blocks for Voice.

### CODE REVIEW

**Comment by mheap** [comment]
These all render successfully. It looks as though there are two examples missing:

* http://localhost:3000/voice/voice-api/building-blocks/download-a-recording (GET request using a JWT)
* http://localhost:3000/voice/voice-api/building-blocks/transfer-a-call (PUT to a leg UUID with a new NCCO url)

**Comment by lornajane** [comment]
Ah, I thought I was just "filling some gaps" - I took at stab at the things I understood well and thought I could test.  I'm sure there are others we could add, do you want to hold these examples until we have them all?

**Comment by mheap** [comment]
As far as I can tell, those are the only two missing blocks. Once they're added that's 100% coverage for outbound requests in VAPI using `curl`

**Comment by mheap** [comment]
Merging as the remaining blocks will take a little while to put together

**Pull request merged**
