### PR TITLE
Pricing documentation

### LINKED ISSUE #366: Pricing API is not fully documented

### PR DESCRIPTION
**Pull request by tommorris**
* Documents all four of the pricing endpoints with code samples
* Moves the pricing endpoints to their own page
* Rearranged code samples for pricing endpoints into a more logical directory structure
* Fixed an incorrect description on the settings endpoint

This fixes #366.

### CODE REVIEW

**Comment by adambutler** [comment]
Please add a description.

**Comment by tommorris** [comment]
@adambutler Done, ready for review.

**Comment by tommorris** [comment]
@adambutler Ah yes, I was going to fix that. Now done. It's all moved to a separate page as well.

**Comment by tommorris** [comment]
Just for internal reference - JIRA ticket: DOCS-296.

**Pull request merged**
