### PR TITLE
Update SDK docs

### PR DESCRIPTION
**Pull request by vonageCI**

### CODE REVIEW

**Comment by tbedford** [comment]
Both [iOS](https://nexmo-developer-pr-2390.herokuapp.com/sdk/stitch/ios/) and [Android](https://nexmo-developer-pr-2390.herokuapp.com/sdk/stitch/android/) SDK docs don't display for me in the Review App.

**Comment by dimitrisniras** [comment]
> Both [iOS](https://nexmo-developer-pr-2390.herokuapp.com/sdk/stitch/ios/) and [Android](https://nexmo-developer-pr-2390.herokuapp.com/sdk/stitch/android/) SDK docs don't display for me in the Review App.

I don't see why they are not redirecting correctly there. I didn't touch the latest files, only the 2.2.0 of Android and Release Notes of iOS. 

Seems that something is not going well with the symlink.

**Comment by tbedford** [comment]
@pardel @fabianrbz - I think sym links were changed over the weekend? Is this related at all?

**Comment by pardel** [comment]
@dimitrisniras the latest symlink was done wrong. Notice the ? at the end of each: 
Screenshot 2020-02-01 at 23 13 03
Screenshot 2020-02-01 at 23 13 21

**Comment by pardel** [comment]
@tbedford Yes - I've submitted a patch and it got merged on Sunday.

**Comment by pardel** [comment]
@dimitrisniras Also, I've noticed 2 extra folders for Android 3.0.0 and 3.1.1. What are they used for?

**Comment by dimitrisniras** [comment]
> @dimitrisniras Also, I've noticed 2 extra folders for Android 3.0.0 and 3.1.1. What are they used for?

Probably they are left there from previous SDK implementations. We have to remove them!

**Comment by dimitrisniras** [comment]
> @dimitrisniras the latest symlink was done wrong. Notice the ? at the end of each:
> Screenshot 2020-02-01 at 23 13 03
> Screenshot 2020-02-01 at 23 13 21

Yeah, I saw that and fixed the symlink, but I don't know why it broke in the beginning.

**Pull request closed without merging**
