### PR TITLE
Add Client SDK changelogs

### PR DESCRIPTION
**Pull request by tbedford**
## Description

Temporary inclusion of Changelogs for upcoming release.

- [x] Add changelogs for each platform. 
- [x] Make SDK section (containing SDK ref and changelog) collapsible for each platform.

## Review

Review app is available.

### CODE REVIEW

**Comment by brittBarak** [comment]
It looks perfect, thank you!
only that the `Setup` entry jumped to the bottom again...

**Comment by tbedford** [comment]
On Setup - that fix was in another PR so is not reflected here. In live docs it's correct.

**Comment by brittBarak** [comment]
> On Setup - that fix was in another PR so is not reflected here. In live docs it's correct.

oh ok that's perfect! thank you

**Comment by brittBarak** [comment]
@tbedford @mheap 
Hi 
I added a first version for the changelogs, which I mostly copy-pasted from the SDKs. The advocates will go through and edit it some more if needed. For now I'd really really love to merge this, as there are some customers who are waiting for it.

- I renamed "changelog" to "release notes" , It seems to be a more commonly used term for that. 
- I have some issue with the review app. the links don't work.. i don't know why though, nor can see logs.

Appreciate your review ! (I can't approve it since I edited the PR)

Thank you so much!!

**Pull request merged**
