### PR TITLE
Update SDK docs

### PR DESCRIPTION
**Pull request by vonageCI**

### CODE REVIEW

**Comment by tbedford** [comment]
#2396 should be resolved first

**Comment by mheap** [comment]
Saved by the smoke!

```
  1) Android docs SDK reference renders successsfully
     Failure/Error: expect(response).to have_http_status(:ok)
       expected the response to have status code :ok (200) but it was :not_found (404)
     # ./spec/requests/sdk-documentation/android_spec.rb:14:in `block (3 levels) in <top (required)>'
```

**Comment by fabianrbz** [comment]
@mheap looks like there is trailing `?` in the symlink
Screenshot 2020-02-14 at 13 31 42

How's the symlink generated?

**Comment by mheap** [comment]
See https://github.com/Nexmo/nexmo-developer/pull/2451

**Pull request closed without merging**
