### PR TITLE
Initial changes for the careers page.

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

Add careers page.

### CODE REVIEW

**Comment by mheap** [comment]
@fabianrbz Please show this to Acacia and get her feedback

**Comment by fabianrbz** [comment]
this have been reviewed by Acacia

**Comment by fabianrbz** [comment]
@mheap In order to wrap this one up, I guess we need to place a link to the careers page somewhere. Also, we could use `replaceState` instead of `pushState`, I don't have any preference.

**Comment by fabianrbz** [comment]
@mheap In order to wrap this one up, I guess we need to place a link to the careers page somewhere. Also, we could use `replaceState` instead of `pushState`, I don't have any preference.

**Comment by mheap** [comment]
@fabianrbz We've aliased to `Technical Support` but the dropdown is no longer in alphabetical order

We should link to this page from `/team` I think.

How about the additional filtering as recommended in the email thread??

> I would suggest developers might be candidate for:
> Product, including DevRel
> Engineering, including QA
> Customer Solutions Architects
> Support Engineers

**Comment by mheap** [comment]
I'd also hide any departments that don't have active roles e.g. `Office of CRO`

**Comment by mheap** [comment]
@fabianrbz The list of departments still needs sorting I think. `Technical Support` appears near the top of the list

**Comment by fabianrbz** [comment]
@mheap done

**Pull request merged**
