### PR TITLE
Create curl-tutorial.md

### PR DESCRIPTION
**Pull request by obodriagovatvonagedotcom**
Reports API command line how-to

## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by tbedford** [comment]
The PR description is a bit vague. Can you explain a bit more about what this is please, and delete the text that is not relevant?  I have a feeling this looks more like a Guide rather than a "building block".

Note, we don't use "building_blocks" anywhere now (or we shouldn't do). The directory would be `code_snippets` and the target code would have to be in the corresponding code snippet repo. Also the markup to include a code snippet is `code_snippet`. Thanks.

**Comment by mheap** [comment]
@tbedford This looks like a good candidate for the task based work. What do you think?

**Comment by tbedford** [comment]
@mheap: yes, when we move to Tasks it would most likely be a Task.

**Comment by obodriagovatvonagedotcom** [comment]
Here is the complete set of CURL examples:

*1. Create report example*
curl -X POST -u $API_KEY:$API_SECRET -H "Content-Type: application/json"
--data '{"account_id": "$API_KEY","product": "SMS","sms_type":
"MT","start_date": "2019-06-01T00:00:00+0000","end_date":
"2019-06-28T23:59:59+0000"}' https://api.nexmo.com/v2/reports/

*2. Response example*
{"request_id":"6c5506b7-f16a-44dc-af06-756bbf467488","request_status":"PENDING","product":"SMS","account_id":"$API_KEY","start_date":"2019-02-27T00:00:00+0000","end_date":"2019-02-28T23:59:59+0000","include_subaccounts":false,"sms_type":"MT","include_message":false,"receive_time":"2019-05-29T16:37:58+0000","_links":{"self":{"href":"/v2/reports/6c5506b7-f16a-44dc-af06-756bbf467488"}},"self_link":"
https://api.nexmo.com/v2/reports/6c5506b7-f16a-44dc-af06-756bbf467488"}

*3. Get report status example*
curl -u $API_KEY:$API_SECRET
https://api.nexmo.com/v2/reports/6c5506b7-f16a-44dc-af06-756bbf467488

*4. Report status response*
{"request_id":"6c5506b7-f16a-44dc-af06-756bbf467488","request_status":"SUCCESS","product":"SMS","account_id":"$API_KEY","start_date":"2019-02-27T00:00:00+0000","end_date":"2019-02-28T23:59:59+0000","include_subaccounts":false,"sms_type":"MT","include_message":false,"file_id":"bd805ad6-756f-46a1-9c29-c58bc68bc77f","url":"
https://api.nexmo.com/v3/media/bd805ad6-756f-46a1-9c29-c58bc68bc77f
","receive_time":"2019-06-17T16:39:06+0000","start_time":"2019-06-17T16:39:06+0000","_links":{"self":{"href":"/v2/reports/6c5506b7-f16a-44dc-af06-756bbf467488"}},"items_count":14952,"self_link":"
https://api.nexmo.com/v2/reports//6c5506b7-f16a-44dc-af06-756bbf467488"}

*5. Download completed report*
curl -u $API_KEY:$API_SECRET -o ./report.zip
https://api.nexmo.com/v3/media/bd805ad6-756f-46a1-9c29-c58bc68bc77f

*Create report with a callback*
It is possible to get an HTTP POST callback notification from Nexmo instead
of polling the report status.
curl -X POST -u $API_KEY:$API_SECRET -H "Content-Type: application/json"
--data '{"account_id": "$API_KEY","product": "SMS","sms_type":
"MT","start_date": "2019-06-01T00:00:00+0000","end_date":
"2019-06-28T23:59:59+0000","callback_url":"https://YOUR_CALLBACK_URL/12356"}'
https://api.nexmo.com/v2/reports/

**Comment by tbedford** [comment]
Oh I see now, this is a set of code snippets for Curl for Reporting API. @mheap: Dare I ask who is looking after Reporting API from DevX? :)

**Comment by mheap** [comment]
@tbedford That'd be me! These snippets already exist on EA, but @obodriagovatvonagedotcom would like them put together as a guide, which is what's making me think about the task based content

**Pull request closed without merging**
