### PR TITLE
Devtv nov2

### PR DESCRIPTION
**Pull request by ruskibenya**
## Description

Content updates for the week of November 16. **This PR should not be merged until November 2nd**

### CODE REVIEW

**Comment by ruskibenya** [comment]
💕 thanks @phazonoverload, totally forgot about labels like a n0o0o0ob

**Comment by ruskibenya** [comment]
@fabianrbz please merge. Thank you!

**Comment by fabianrbz** [comment]
@ruskibenya it has a few conflicts :/

**Review by lornajane — APPROVED** [review]
Rebased, should be good to go  (I'll just watch the build finish first!)

**Pull request merged**
