### PR TITLE
Fix character counter.

### PR DESCRIPTION
**Pull request by fabianrbz**
There was an issue when using 160 '[' characters as the message. It should split the
messages into three.
This also fixes the check for Unicode characters.

### CODE REVIEW

**Comment by mheap** [comment]
I'm not sure this is correct.

This is 80 `]` characters, which is 160 bytes (esc+]) and should fit in a single message

```
]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
```

Instead the calculator shows it as two messages. I believe this is due to the fact that it's now detected as UCS-2 which is 70 characters per message

**Comment by fabianrbz** [comment]
isn't the maximum length 140 bytes? (160 standard GSM 7-bit characters or 70 UCS-2 16-bit characters)

**Comment by mheap** [comment]
Yep, I typed bytes when I meant characters. `]` is 2 GSM 7-bit characters, `esc+]`.

GSM 7-bit letter: 160 characters, 1 message

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

GSM 7-bit letter plus escape character: 159 characters, 1 message

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa]
```

UCS-2 for the entire message due to emoji: 70 characters, 1 message

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa😃
```

**Comment by fabianrbz** [comment]
@mheap this is ready for another pass

**Pull request merged**
