### PR TITLE
Numbers Guide WIP

### PR DESCRIPTION
**Pull request by adambutler**
## Description

The new guide:

✓ reuses existing building block content
✓ adds new examples for searching for, buying and linking numbers (for cURL and `nexmo-cli`, will need code samples for libraries)

still needs:

:telephone_receiver: SIP (maybe)
:iphone: how to link numbers to incoming SMS - probably a shared example with the webhooks guide
:electric_plug: examples might need to be moved to have the new “multi-step” style

## Deploy Notes

TBD

### CODE REVIEW

**Comment by tommorris** [comment]
Changed target base to `master` since `content/sms` has been merged.

**Comment by tbedford** [comment]
I've assigned myself to take a look into this - it looks like a new topic. I will test locally and review before merging.

**Comment by lornajane** [comment]
I'm not sure what this document gives us over https://developer.nexmo.com/account/guides/numbers other than it includes some example code which I think we'd prefer to have in building blocks.  It does show how to redirect your number to another number, which I've not seen elsewhere.

**Comment by lornajane** [comment]
This has quite a lot of overlap with our existing content in the Account section, it would be simpler not to duplicate things.

**Pull request closed without merging**
