### PR TITLE
Update SDK docs

### PR DESCRIPTION
**Pull request by dimitrisniras**

### CODE REVIEW

**Comment by dimitrisniras** [comment]
@fabianrbz The errors that I am getting here are for Ruby and not for the SDKs

**Comment by dimitrisniras** [comment]
> Two different copyright notices.
> 
> sdk-docs-2

@horothesun

**Comment by tbedford** [comment]
@fabianrbz also seems to have the Ruby build issue.

**Comment by dimitrisniras** [comment]
Closing this one, and reopen with the fixes in iOS.

**Pull request closed without merging**
