### PR TITLE
Update to Vonage curl code snippets

### PR DESCRIPTION
**Pull request by mheap**
## Description

Replace the Nexmo cURL code snippets with Vonage code snippets

## Deploy Notes

N/A

### CODE REVIEW

**Comment by tbedford** [comment]
Looking at https://nexmo-developer-pr-3266.herokuapp.com/messaging/sms/code-snippets I get an error.

**Comment by mheap** [comment]
@tbedford That's due to redirects not working without a database

Start from https://nexmo-developer-pr-3266.herokuapp.com/messaging/sms/code-snippets/send-an-sms and things work

**Comment by tbedford** [comment]
> @tbedford That's due to redirects not working without a database
> 
> Start from https://nexmo-developer-pr-3266.herokuapp.com/messaging/sms/code-snippets/send-an-sms and things work

I was starting from the landing page: https://nexmo-developer-pr-3266.herokuapp.com and then clicking on "Code snippets" in one of the product boxes.

**Comment by mheap** [comment]
@tbedford Yep, that's expected on review apps due to a missing database

**Review by lornajane — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
