### PR TITLE
Add "Nexmo is now Vonage" image

### PR DESCRIPTION
**Pull request by lornajane**
## Description

We're going to need to add an image to all our GitHub READMEs to aid our brand transition, this is a good and reliable place to host it!

### CODE REVIEW

**Comment by mheap** [comment]
@fabianrbz Does this image already exist in the rebrand branch? If so, should we point to that?

**Comment by fabianrbz** [comment]
@mheap @lornajane we don't, we have something similar for the header and footer, but that was built with html and css

**Comment by lornajane** [comment]
OK, Isaac is happy so if we can merge sometime, that would be great!

**Comment by mheap** [comment]
:shipit:

**Pull request merged**
