### PR TITLE
Add new env variable DOCS_BASE_PATH to .env.example and docker-compose.

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

Add new env variable DOCS_BASE_PATH to .env.example and docker-compose.

### CODE REVIEW

**Comment by mheap** [comment]
Should we also default to the current directory for backwards compatibility?

**Comment by fabianrbz** [comment]
@mheap what do you mean? it's using the current directory, so it should work as before.

**Comment by mheap** [comment]
https://github.com/Nexmo/nexmo-developer/blob/master/config/application.rb#L37

Should this be

```
config.docs_base_path = ENV['DOCS_BASE_PATH'] || '.'
```

So that we don't impact existing review apps / local installations?

**Comment by fabianrbz** [comment]
@mheap review apps pick it up from `app.json` and with this docker will work too.
Only local installs will require to update the `.env`. Anyway, updating the code wouldn't hurt, so I'm on it :D

**Comment by mheap** [comment]
New review apps pick it up from `app.json`, but existing ones don't - plus the impact on existing local installs. We have the opportunity to make this backwards compatible, and we should take it (which I see you're already doing!)

**Comment by mheap** [comment]
@fabianrbz Something I was just hit by - do we expect them to specify the trailing `/` on the `DOCS_BASE_PATH`? We expect them to on `nexmo-oas-renderer` but it looks as though we don't in NDP. Can we make it handle both cases?

**Comment by fabianrbz** [comment]
@mheap you are right, I'm guessing we want to include the trailing `/`. I'll do that as part of a new PR. Given that this is just a fix to allow people to use docker

**Pull request merged**
