### PR TITLE
DEVX-1863: Allow locale in url

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

Allow locale in url and fallback to `en`.

## Deploy Notes

We need to release `nexmo-markdown-renderer` before merging this.

### CODE REVIEW

**Comment by tbedford** [comment]
@fabianrbz there are now some merge conflicts sadly. Would @benhayehudi be able to review this one?

**Comment by benhayehudi** [comment]
Started reviewing this and I see that we make a lot of changes to the markdown filters here. Would it be possible to make those changes in the https://github.com/Nexmo/nexmo-markdown-renderer since that will soon be the source of truth for the markdown pipeline instead?

**Comment by mheap** [comment]
@fabianrbz I've fixed the conflicts in here and the review looks good.

As we're not supporting internationalised use cases etc, should we disable those routes so that we can get some of these refactors merged and then revisit that problem in a future PR?

**Comment by fabianrbz** [comment]
@mheap i'll take a look at this, looks like something went wrong with the merge.
I'll undo the changes for use_cases, should I do the same for tutorials?

**Comment by mheap** [comment]
@fabianrbz 👍. Let me know what mistakes I made when resolving conflicts too please

**Comment by fabianrbz** [comment]
@mheap do we need to drop the locale for those urls? if we do that we'll lose the current locale

**Comment by mheap** [comment]
@fabianrbz For now, yes please. We'll need those pages localised in the future, but for v1 we don't want duplicate content warnings.

My thoughts are that we support locales for markdown content to start, then revisit tutorials, use cases etc at a later date

**Comment by fabianrbz** [comment]
@mheap done, let's wait for the CI and the review app, I want to test it there as well

**Comment by mheap** [comment]
@fabianrbz Mostly looks good. I saw a few issues

* If I visit a `/en` page on `developer.nexmo.com` should it redirect me to the canonical URL (without the locale in the URL)?
* If we can't load a `cn` page and fall back to `en`, the canonical URL generated should point to the `en` URl not the same page
* Locale still exists on tools, landing pages and extend

**Comment by fabianrbz** [comment]
@mheap done. We'll need to add a few changes once we set the locale from the domain though

**Comment by mheap** [comment]
@fabianrbz Looking at the changes we're almost there on the canonical thing. Instead of redirecting, we want to keep `cn` in the URL (so that we show the correct links in the sidebar) but have the `rel=canonical` tag in the header point to the `en` page

https://github.com/Nexmo/nexmo-developer/blob/afe250d7706fc02e5eea5f9bcc6b09b66dd023bd/app/helpers/application_helper.rb#L34

https://github.com/Nexmo/nexmo-developer/blob/75a410630cfaa540d329ec5af81a9f422724e883/app/controllers/tutorial_controller.rb#L58

**Comment by fabianrbz** [comment]
@mheap fixed it. Although we removed the locale from tutorials and use_cases. So those links in the sidenav will point to urls without locales, hence, the canonical url should be fine.

**Comment by mheap** [comment]
@fabianrbz 

✅  https://nexmo-developer-pr-2255.herokuapp.com/messaging/sms/overview shows itself as canonical

✅  https://nexmo-developer-pr-2255.herokuapp.com/en/messaging/sms/overview redirects 

🔴  https://nexmo-developer-pr-2255.herokuapp.com/cn/messaging/sms/overview shows https://nexmo-developer-pr-2255.herokuapp.com/en/messaging/sms/overview as canonical. Should this be without the `/en`?

**Comment by fabianrbz** [comment]
🤦‍♂ @mheap fixed

**Comment by mheap** [comment]
* API Page still allows locale in URL (we're not translating API refs) - https://nexmo-developer-pr-2255.herokuapp.com/en/api
* When we have a locale in the URL that falls back to English, the sidebar isn't expanded - https://nexmo-developer-pr-2255.herokuapp.com/cn/messaging/sms/overview
* Redirects that have a locale prefix but don't direct to a markdown controller 404 e.g. https://nexmo-developer-pr-2255.herokuapp.com/cn/client-sdk/sdk-documentation/android/android (this may be an edge case that we don't fix as I had to manually update the URL here. Worth noting for the future when we have a CN based nav)

**Comment by fabianrbz** [comment]
@mheap done

**Pull request merged**
