### PR TITLE
Add voyager information

### PR DESCRIPTION
**Pull request by victorsteven**
- I added my information to the voyager's page.
@phazonoverload

### CODE REVIEW

**Comment by phazonoverload** [comment]
Could you replace the image with a square one please? 😃

**Comment by victorsteven** [comment]
> Could you replace the image with a square one please? 😃

Okay, I will.

**Comment by phazonoverload** [comment]
How you getting on with this @victorsteven?

**Comment by victorsteven** [comment]
Hi @phazonoverload, I have updated the image.

**Review by phazonoverload — APPROVED** [review]

**Comment by phazonoverload** [comment]
Thanks for this @victorsteven!

**Pull request merged**
