### PR TITLE
Fix incorrect line numbers

### PR DESCRIPTION
**Pull request by tbedford**
## Description

Fix incorrect line number for Python code snippet.

Was based on #3300 - but we had problems with review apps for forks.

## Review

* [Page to review](https://nexmo-developer-pr-3302.herokuapp.com/voice/voice-api/code-snippets/make-an-outbound-call-with-ncco)

### CODE REVIEW

**Comment by tbedford** [comment]
@javiermolsanz - Sorry Javier, we're having some issues on our side with forks right now. I've taken the liberty of recreating your fix here. Hope that's OK. Thanks, Tony.

**Review by javiermolsanz — APPROVED** [review]
No problem at all. The goal is to improve it for our customers :)

**Comment by tbedford** [comment]
Thanks Javier!

**Comment by marklewin** [comment]
Removing @niati because he's away today

**Review by marklewin — APPROVED** [review]
Swapped client and code blocks

**Pull request merged**
