### PR TITLE
Slim sidebar navigation

### PR DESCRIPTION
**Pull request by mheap**
## Description

This PR scopes the sidebar navigation to the current active product, and reformats the top bar links to contain a list of all products

## Deploy Notes

N/A

### CODE REVIEW

**Comment by cr0wst** [comment]
I like this idea. A few notes right now that I mentioned in Slack:

Mobile is broken. The extra links don't scroll like they do on the current deployment.
image
image

Where did the search bar go?

Overall I like the idea. I'm not a fan of the current left navigation and this improves it quite a bit.

**Comment by mheap** [comment]
Search isn't enabled on review apps as there's no Algolia key but I can enable for this app specifically so that we can see how it looks.

The nav needs work on mobile, but if we think this is a good direction to go in I'll spend some time polishing up this PR

**Comment by lornajane** [comment]
Do we need a WIP flag on this or something? I sat down to review without realising this is a starting point rather than a finished offering.  Personally I really like it - if we can call the "Overview" page the name of the product/section that would really help. And we need a "Back to full list" link or something at the top of the nav IMO. It seems to make the left hand menu behave/scroll differently but possibly better.

Do we need to rebase to bring in the changes to tutorial navigation to consider that as well as this?

**Comment by mheap** [comment]
Yeah this is WIP. The overview page titles need updating, I agree.

This is parked for now as the top navigation needs some love, but I'll pick it up towards the end of March

**Comment by mheap** [comment]
Closing until the design time has time to build the required components

**Pull request closed without merging**
