### PR TITLE
Add Node.js Code Snippets for Verify PSD2 Requests

### PR DESCRIPTION
**Pull request by AlexLakatos**
## Description
We're adding support for PSD2 in the Node.js SDK, so adding the code snippets for it here. This is the last PR in a chain, so please don't merge before the nexmo-node 2.7.1 release and the code snippet repo PR gets merged.

https://github.com/Nexmo/nexmo-node/pull/305
https://github.com/Nexmo/nexmo-node-code-snippets/pull/86

### CODE REVIEW

**Comment by benhayehudi** [comment]
@dragonmantank Is someone going to close the circle on the Node release + the connected PRs in the code snippets repo and here on NDP? 🙏

**Comment by lornajane** [comment]
That'll be me if nobody beats me to it since I can manage enough JS to own the Verify stuff I'm already familiar with :)

**Comment by benhayehudi** [comment]
Closing this PR in favor of an eventual new one once there are code snippets with correct line numbers, etc.

**Comment by lornajane** [comment]
Sorry, I am just looking at the code snippets now, I'll keep this open if that's OK?

**Pull request merged**
