### PR TITLE
update ios client sdk config docs

### PR DESCRIPTION
**Pull request by abdulajet**
## Description

Ticket: https://nexmoinc.atlassian.net/browse/DEVX-3848 (add objc)
- Old: https://developer.nexmo.com/client-sdk/configuration/configure-data-center/swift
- New: https://nexmo-developer-pr-3113.herokuapp.com/client-sdk/configuration/configure-data-center/objective_c

Ticket: https://nexmoinc.atlassian.net/browse/DEVX-3849 (add swift)
- Old: https://developer.nexmo.com/client-sdk/configuration/configure-ice-server/objective_c
- New: https://nexmo-developer-pr-3113.herokuapp.com/configuration/configure-ice-server/swift

### CODE REVIEW

**Comment by tbedford** [comment]
@fabianrbz - it looks like the syntax highlighter might not handle `//` in links correctly? Here: https://nexmo-developer-pr-3113.herokuapp.com/client-sdk/configuration/configure-data-center/objective_c

**Comment by tbedford** [comment]
@fabianrbz - Also Objective-C and Swift tabs sometimes get stuck. I've also seen this in the live docs:

image

**Comment by fabianrbz** [comment]
@tbedford looks like it's an upstream issue https://prismjs.com/test.html#language=objectivec
I've tried it there and it gets rendered in the same way :/, I believe it's an issue with `@"`.

I thought we fixed the second issue a while back, I'll take a look.

**Review by tbedford — APPROVED** [review]
LGTM. I think we can't fix the Prism.js issue right now. Also Fabian will look into the other issue and provide a fix if required in another PR.

**Pull request merged**
