### PR TITLE
Messages API documentation: WhatsApp conversation-based pricing

### PR DESCRIPTION
**Pull request by superchilled**
## Description

Adding information to Messages API documentation about the conversation-based pricing model now offered by Vonage for sending WhatsApp messages. Information consists of an overview and some links to further info.

## Deploy Notes

Content update only.

### CODE REVIEW

**Review by smackellar — CHANGES_REQUESTED** [review]
a 24-hour period starting from the time the first message is sent **by the business**
need to add and emphasise this as it's a point often missed

**Comment by superchilled** [comment]
> a 24-hour period starting from the time the first message is sent **by the business** need to add and emphasise this as it's a point often missed

Thanks Stuart. I've made a small update to emphasise this. I'm still not sure how the information we've added inter-relates to the section above on the Customer Care Window. Do you think that needs clarifying at all, or should we just merge this?

**Review by smackellar — COMMENTED** [review]
Small error: "with pricing model" should be "with the pricing model"

**Review by smackellar — COMMENTED** [review]
Rules for messaging customers (to replace Important WhatsApp rules)

WhatsApp has a concept of a 24 hour customer care window, during which a business can freely message an end user. The 24 hour window can be initiated in two ways:
- An end user sends a message to the business
- A business sends a templated message to the end user. The 24 hour window starts as soon as the end user replies.
Templates must be approved by WhatsApp before they can be used to send messages to an end user. When the 24 hour window expires, a new 24 hour customer care window must be initiated again.
It is important to be aware that 24 hour customer care windows are not the same as the 24 hour billable conversation window.

**Review by abdulajet — APPROVED** [review]

**Pull request merged**
