### PR TITLE
[DEVX-2029] Filter tutorials by programming languages.

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

Add programming languages dropdown to `/tutorials`.

## Note

I'm not sure why we are excluding those languages for use-cases.

### CODE REVIEW

**Comment by tbedford** [comment]
@fabianrbz - when I go to `/tutorials` I was expecting to see new languages in the drop down. Not sure I understand the purpose of this PR. If you can clarify in the description I can take another look. Thanks!

**Comment by fabianrbz** [comment]
@tbedford the dropdown wasn't there before, i added the same languages that we have in `/use-cases`. Do you want to add the mobile ones? 
For some reason we are excluding these `['csharp', 'javascript', 'kotlin', 'android', 'swift', 'objective_c']` we might want to add them for both.

**Comment by tbedford** [comment]
Yes, we should add those for both. Client SDK team are working on multi-language tutorials.

**Comment by fabianrbz** [comment]
@tbedford done

**Pull request merged**
