### PR TITLE
Bibi dotnet building blocks

### PR DESCRIPTION
**Pull request by RabebOthmani**
I added the building blocks for SMS, Number Insights and Verify.

### CODE REVIEW

**Comment by mheap** [comment]
@marklewin I recall something about this branch and the NI work that you're doing. What can we do to get it merged?

**Comment by marklewin** [comment]
The Number Insight blocks have been moved to the YAML format and the SMS ones are in the process of being moved. Verify isn't ready for them yet, so leaving this PR open for the time being but keeping "don't merge" label.

**Comment by mheap** [comment]
@marklewin With the Verify update, can we close this PR?

**Comment by marklewin** [comment]
Yes we can! Everything that Bibi kindly provided here has been incorporated into the NI, SMS and Verify building blocks. If you're happy, could you please close this PR?

**Comment by mheap** [comment]
Thanks for this @RabebOthmani - we've now finished porting NI and Verify and your building blocks are being put to good use!

**Pull request closed without merging**
