### PR TITLE
Added icons for Swift and Objective-C

### PR DESCRIPTION
**Pull request by benhayehudi**
This PR addresses DEVX-821 ticket in Jira. Whereas there were previously no icons for Swift and Objective-C tabbed content, this PR adds those icons.

### CODE REVIEW

**Comment by pardel** [comment]
@benhayehudi could we use the Apple logo for Objective-C but the official Swift logo for Swift?

**Comment by benhayehudi** [comment]
> @benhayehudi could we use the Apple logo for Objective-C but the official Swift logo for Swift?

Hi @pardel, let's check with @mheap and see what he says. He advised me to keep it in line with what we are already doing (i.e. https://developer.nexmo.com/client-sdk/in-app-voice/building-blocks/answer-call).

**Comment by mheap** [comment]
For this PR let's keep it consistent with what we're doing on the building blocks. I'm not opposed to a follow-up PR that changes the icons everywhere on NDP though

**Comment by benhayehudi** [comment]
If that's the case, @pardel, are you good with moving forward on this PR? I'd be glad to update the Objective-C logo system wide in a separate PR, as @mheap suggests.

**Comment by pardel** [comment]
@benhayehudi Sure thing!

**Comment by benhayehudi** [comment]
> @benhayehudi Sure thing!

Great. @mheap, can you go ahead and approve + merge? Thanks!

**Pull request merged**
