### PR TITLE
Fixed some typos and grammatical errors

### PR DESCRIPTION
**Pull request by zaffnet**
Fixed some minor grammatical errors.

Contributed as a part of Hacktoberfest 2018.

### CODE REVIEW

**Comment by zaffnet** [comment]
@tbedford Any changes you suggest?

**Comment by tbedford** [comment]
Yes, I put my requested changes as inline comments to my review. If you can just fix those then I can approve and merge. Thanks.

**Comment by zaffnet** [comment]
@tbedford, I am not able to see your review

**Comment by tbedford** [comment]
Thank you!

**Pull request merged**
