### PR TITLE
vonage-python-code-snippets Update

### PR DESCRIPTION
**Pull request by NexmoDev**

### CODE REVIEW

**Comment by lornajane** [comment]
@superdiana Does this PR need anything else before it can merge?

**Comment by tbedford** [comment]
@lornajane - there wasn't a review app. I've kicked one off and should get back and review this tomorrow. It's possible there are some NDP configs to be done.

**Comment by tbedford** [comment]
Yes, looks like the config has not been updated. I will do that today on this PR.

**Review by tbedford — APPROVED** [review]
Looks good in review app.

**Pull request merged**
