### PR TITLE
Updated firewall details

### PR DESCRIPTION
**Pull request by peter-nexmo**
Added Dallas DC firewall details, and removed Washington DC firewall details.

## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by mheap** [comment]
Thanks @peter-nexmo! We were thinking about removing these IP addresses and linking to the knowledgebase as the source of truth for this info. Any thoughts @lornajane?

**Comment by lornajane** [comment]
Yes there is an issue open to remove them since we don't get notified of changes. We should point to the knowledgebase resource for the list of IPs

**Comment by peter-nexmo** [comment]
That's a whole other process we are working on, so that Support is notified of these changes also, which we currently are not.

**Comment by mheap** [comment]
Would your current preference be to merge this PR and revisit with a link to the KB in the future?

**Pull request merged**
