### PR TITLE
[WIP] Managed Programmes

### PR DESCRIPTION
**Pull request by adambutler**
## Description

🚧 Work in progress.

Adds support for having content that can only be accessed by authenticated users.

## Deploy Notes

- [ ] Requires migration (auto)
- [ ] Requires environment variables.

### CODE REVIEW

**Comment by lornajane** [comment]
This feature seems useful but I don't think we can base on an outdated WIP branch, so I'll close this.

**Comment by mheap** [comment]
I'll update this with master. The majority of the work is done here, we just need to implement `protected_resource?` to read from a database and match against the URL

**Comment by mheap** [comment]
I've created a Jira ticket to get this merged. I'll look at it next week

**Comment by lornajane** [comment]
Not currently needed

**Pull request closed without merging**
