### PR TITLE
[DEVX-2029] Remove DotNet.

### PR DESCRIPTION
**Pull request by fabianrbz**
## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by tbedford** [comment]
@fabianrbz - sorry, what exactly is the purpose of this PR please? Thanks.

**Comment by fabianrbz** [comment]
@tbedford it looks like i couldn't push in the previous branch and the commit was missing. This removes the exceptions that we have (`['csharp', 'javascript', 'kotlin', 'android', 'swift', 'objective_c']`) and drops `dotnet` from the dropdown, we already have `csharp`

**Comment by tbedford** [comment]
If I go [here](https://nexmo-developer-pr-2704.herokuapp.com/tutorials) I see .NET in the drop down. Should I?

**Comment by fabianrbz** [comment]
@tbedford that's actually csharp, so yes

**Pull request merged**
