### PR TITLE
Updating all codesnippets with new csharp codesnippets project

### PR DESCRIPTION
**Pull request by RabebOthmani**
## Description

Please describe what the changes are made in this pull request and why the change was necessary.

## Deploy Notes

Notes regarding deployment the contained body of work. These should note any db migrations, etc.

### CODE REVIEW

**Comment by lornajane** [comment]
Yes we should be pointing to master, it was pointing elsewhere in the past. I was asked how to change the default branch on the code snippets repo for .NET but it didn't get done before I revoked Bibi's access. Let me know if I can help untangling some of this.

**Comment by RabebOthmani** [comment]
@mheap @lornajane @marklewin I have the changes locally, would it help if I try a new PR?

**Comment by marklewin** [comment]
> @mheap @lornajane @marklewin I have the changes locally, would it help if I try a new PR?

Thans @RabebOthmani, but I don't know TBH! @lornajane: I would really appreciate your input here, when you have time.

**Comment by mheap** [comment]
@marklewin I've updated the submodule to point to master and made the Github links on the page point to master too. Some of the line numbers aren't correct (I checked some voice snippets and the indentation is off).

This looks like a useful PR, but each of the .NET code snippets will need checking manually before we can merge

**Comment by marklewin** [comment]
Thanks. Yes, I'll look at these shortly.

**Comment by marklewin** [comment]
Checked all snippets. Many OK, but some required fixing:

Account
- Configure OK
- Get balance FIXED
- Create secret FIXED
- Fetch secret FIXED
- List all secrets FIXED
- Revoke FIXED

Application
- Create OK
- Delete FIXED
- Get FIXED
- List FIXED
- Update OK

SMS
- DLR OK
- Receive OK
- Send OK
- Send Unicode OK

Number Insight
- Advanced sync OK
- Basic OK
- Standard OK

Numbers
- Buy FIXED
- Cancel FIXED
- Search OK
- Update OK

Verify
- Cancel OK
- Check OK
- Search OK
- Send OK
- Trigger next OK

Voice
- Connect inbound call OK
- Connect callers to conf OK
- Earmuff OK
- Handle DTMF OK
- Outbound call with NCCO OK
- Outbound call OK
- Mute OK
- Play audio into call OK
- Play DTMF into call OK
- Play TTS into call OK
- Receive inbound call OK
- Retrieve call info FIXED
- Transfer OK

**Pull request merged**
