### PR TITLE
Fix IconFilter regex

### PR DESCRIPTION
**Pull request by tommorris**
Previous regex was throwing an error as the square bracket was unescaped

### CODE REVIEW

**Comment by adambutler** [comment]
@tommorris What scenario caused this to error? If I know I can capture it in a spec to prevent regressions.

**Comment by tommorris** [comment]
@adambutler It was coming up in Heroku logs earlier. I think the logging suppress the error in development.

**Comment by adambutler** [comment]
@tommorris Are you still able to pull what you saw in logs? I've not seen this issue raised as an exception anywhere. Also, I'm not aware of any exception suppression in development that could affect this part of the application.

**Comment by adambutler** [comment]
I stumbled upon the warning in question today:

```
~/Developer/nexmo-developer/app/filters/icon_filter.rb:6: warning: regular expression has ']' without escape: /\[icon="(.+?)"]/
```

Confirming the issue I'm happy for this to now be merged.

**Pull request merged**
